name: Test

on: [push, pull_request]

env:
    GOEXPERIMENT: cgocheck2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GO_VERSION:
          - "oldstable"
          - "stable"

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install SoftHSM
      run: sudo apt-get install -y softhsm2

    - name: Set up Go ${{ matrix.GO_VERSION }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.GO_VERSION }}
        cache: false

    - name: Test
      run: ./test.sh
