name: Test

on: [push, pull_request]

env:
    GODEBUG: cgocheck=2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GO_VERSION:
          - "1.17.8"
          - "1.20.4"
          - "1.20.5"

    env:
      GO_VERSION: ${{ matrix.GO_VERSION }}

    steps:
    - uses: actions/checkout@v3

    - name: Install SoftHSM
      run: sudo apt-get install -y softhsm

    - name: Set up Go ${GO_VERSION}
      uses: actions/setup-go@v4
      with:
        go-version: ${GO_VERSION}
        cache: false

    - name: Test
      run: ./test.sh
